#!/usr/bin/env bash
# Run a command inside node:20-bookworm against this repo.
# Why: engines pins node ^20 / npm ^10 (host has node 22 / npm 11 — a lockfile
# generated by npm 11 is one CI rejects, playbook §0.4), and rollup@4.62+ needs
# GLIBC 2.32 while this box has 2.31, so host `npx vitest` dies with
# ERR_DLOPEN_FAILED (playbook §7).
set -euo pipefail
REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
exec docker run --rm \
	-u "$(id -u):$(id -g)" \
	-v "${REPO}:/app" -w /app \
	-e HOME=/tmp \
	-e npm_config_cache=/tmp/.npm \
	${NODEENV_DOCKER_ARGS:-} \
	node:20-bookworm \
	bash -lc "$*"
