var classes = [
    {
        "name": "OCA\\DocuDesk\\Controller\\HealthController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 5,
        "ccnMethodMax": 5,
        "externals": [
            "OCP\\AppFramework\\Controller",
            "OCP\\IRequest",
            "OCP\\IDBConnection",
            "Psr\\Log\\LoggerInterface",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\Server",
            "OCP\\AppFramework\\Http\\JSONResponse"
        ],
        "parents": [
            "OCP\\AppFramework\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 71,
        "vocabulary": 26,
        "volume": 333.73,
        "difficulty": 7.8,
        "effort": 2603.1,
        "level": 0.13,
        "bugs": 0.11,
        "time": 145,
        "intelligentContent": 42.79,
        "number_operators": 19,
        "number_operands": 52,
        "number_operators_unique": 6,
        "number_operands_unique": 20,
        "cloc": 32,
        "loc": 69,
        "lloc": 37,
        "mi": 90.95,
        "mIwoC": 47.45,
        "commentWeight": 43.5,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 100,
        "relativeDataComplexity": 0.27,
        "relativeSystemComplexity": 100.27,
        "totalStructuralComplexity": 200,
        "totalDataComplexity": 0.55,
        "totalSystemComplexity": 200.55,
        "package": " OCA\\DocuDesk\\Controller\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\DocuDesk\\Controller\\SettingsController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getObjectService",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getConfigurationService",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 6,
        "ccnMethodMax": 3,
        "externals": [
            "OCP\\AppFramework\\Controller",
            "OCP\\IRequest",
            "Psr\\Container\\ContainerInterface",
            "OCP\\App\\IAppManager",
            "OCP\\IGroupManager",
            "OCP\\IUserSession",
            "Psr\\Log\\LoggerInterface",
            "OCA\\DocuDesk\\Service\\SettingsService",
            "RuntimeException",
            "RuntimeException",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse"
        ],
        "parents": [
            "OCP\\AppFramework\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 81,
        "vocabulary": 33,
        "volume": 408.6,
        "difficulty": 8.08,
        "effort": 3300.2,
        "level": 0.12,
        "bugs": 0.14,
        "time": 183,
        "intelligentContent": 50.59,
        "number_operators": 21,
        "number_operands": 60,
        "number_operators_unique": 7,
        "number_operands_unique": 26,
        "cloc": 62,
        "loc": 110,
        "lloc": 48,
        "mi": 90.14,
        "mIwoC": 44.23,
        "commentWeight": 45.9,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.63,
        "relativeSystemComplexity": 121.63,
        "totalStructuralComplexity": 605,
        "totalDataComplexity": 3.17,
        "totalSystemComplexity": 608.17,
        "package": " OCA\\DocuDesk\\Controller\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 10,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\DocuDesk\\Controller\\DashboardController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "page",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "OCP\\AppFramework\\Controller",
            "OCP\\IRequest",
            "OCP\\AppFramework\\Http\\TemplateResponse",
            "OCP\\AppFramework\\Http\\TemplateResponse",
            "OCP\\AppFramework\\Http\\TemplateResponse"
        ],
        "parents": [
            "OCP\\AppFramework\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 19,
        "vocabulary": 12,
        "volume": 68.11,
        "difficulty": 2.5,
        "effort": 170.29,
        "level": 0.4,
        "bugs": 0.02,
        "time": 9,
        "intelligentContent": 27.25,
        "number_operators": 4,
        "number_operands": 15,
        "number_operators_unique": 3,
        "number_operands_unique": 9,
        "cloc": 33,
        "loc": 50,
        "lloc": 17,
        "mi": 107.64,
        "mIwoC": 60.05,
        "commentWeight": 47.58,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.17,
        "relativeSystemComplexity": 5.17,
        "totalStructuralComplexity": 8,
        "totalDataComplexity": 2.33,
        "totalSystemComplexity": 10.33,
        "package": " OCA\\DocuDesk\\Controller\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\DocuDesk\\Controller\\ConsentController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "byDocument",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 39,
        "ccn": 34,
        "ccnMethodMax": 9,
        "externals": [
            "OCP\\AppFramework\\Controller",
            "OCP\\IRequest",
            "Psr\\Log\\LoggerInterface",
            "OCA\\DocuDesk\\Service\\ConsentService",
            "OCA\\DocuDesk\\Service\\SettingsService",
            "OCP\\IL10N",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse"
        ],
        "parents": [
            "OCP\\AppFramework\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 349,
        "vocabulary": 62,
        "volume": 2078.01,
        "difficulty": 21.14,
        "effort": 43932.36,
        "level": 0.05,
        "bugs": 0.69,
        "time": 2441,
        "intelligentContent": 98.29,
        "number_operators": 100,
        "number_operands": 249,
        "number_operators_unique": 9,
        "number_operands_unique": 53,
        "cloc": 89,
        "loc": 204,
        "lloc": 115,
        "mi": 69.94,
        "mIwoC": 27.24,
        "commentWeight": 42.69,
        "kanDefect": 1.24,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 1.3,
        "relativeSystemComplexity": 197.3,
        "totalStructuralComplexity": 1176,
        "totalDataComplexity": 7.8,
        "totalSystemComplexity": 1183.8,
        "package": " OCA\\DocuDesk\\Controller\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\DocuDesk\\Controller\\MetadataController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "enrich",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 11,
        "ccn": 10,
        "ccnMethodMax": 10,
        "externals": [
            "OCP\\AppFramework\\Controller",
            "OCP\\IRequest",
            "Psr\\Log\\LoggerInterface",
            "OCA\\DocuDesk\\Service\\MetadataService",
            "OCP\\IL10N",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse"
        ],
        "parents": [
            "OCP\\AppFramework\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 96,
        "vocabulary": 36,
        "volume": 496.31,
        "difficulty": 9.86,
        "effort": 4892.23,
        "level": 0.1,
        "bugs": 0.17,
        "time": 272,
        "intelligentContent": 50.35,
        "number_operators": 27,
        "number_operands": 69,
        "number_operators_unique": 8,
        "number_operands_unique": 28,
        "cloc": 38,
        "loc": 71,
        "lloc": 33,
        "mi": 91.95,
        "mIwoC": 46.65,
        "commentWeight": 45.29,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 1.06,
        "relativeSystemComplexity": 50.06,
        "totalStructuralComplexity": 98,
        "totalDataComplexity": 2.13,
        "totalSystemComplexity": 100.13,
        "package": " OCA\\DocuDesk\\Controller\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\DocuDesk\\Controller\\MetricsController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "countDocuments",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "countTemplates",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 4,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 7,
        "ccnMethodMax": 4,
        "externals": [
            "OCP\\AppFramework\\Controller",
            "OCP\\IRequest",
            "OCP\\IConfig",
            "OCP\\IDBConnection",
            "Psr\\Log\\LoggerInterface",
            "OCP\\AppFramework\\Http\\TextPlainResponse",
            "OCP\\AppFramework\\Http\\TextPlainResponse"
        ],
        "parents": [
            "OCP\\AppFramework\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 243,
        "vocabulary": 77,
        "volume": 1522.83,
        "difficulty": 10.03,
        "effort": 15272.43,
        "level": 0.1,
        "bugs": 0.51,
        "time": 848,
        "intelligentContent": 151.84,
        "number_operators": 70,
        "number_operands": 173,
        "number_operators_unique": 8,
        "number_operands_unique": 69,
        "cloc": 49,
        "loc": 130,
        "lloc": 81,
        "mi": 75.85,
        "mIwoC": 35.14,
        "commentWeight": 40.7,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 400,
        "relativeDataComplexity": 0.39,
        "relativeSystemComplexity": 400.39,
        "totalStructuralComplexity": 1600,
        "totalDataComplexity": 1.57,
        "totalSystemComplexity": 1601.57,
        "package": " OCA\\DocuDesk\\Controller\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 6,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\DocuDesk\\Controller\\TemplatesController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "index",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "show",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "create",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "update",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "destroy",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 6,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 23,
        "ccn": 18,
        "ccnMethodMax": 6,
        "externals": [
            "OCP\\AppFramework\\Controller",
            "OCP\\IRequest",
            "Psr\\Log\\LoggerInterface",
            "OCA\\DocuDesk\\Service\\TemplateService",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse"
        ],
        "parents": [
            "OCP\\AppFramework\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 218,
        "vocabulary": 42,
        "volume": 1175.53,
        "difficulty": 20.59,
        "effort": 24205.13,
        "level": 0.05,
        "bugs": 0.39,
        "time": 1345,
        "intelligentContent": 57.09,
        "number_operators": 67,
        "number_operands": 151,
        "number_operators_unique": 9,
        "number_operands_unique": 33,
        "cloc": 82,
        "loc": 175,
        "lloc": 93,
        "mi": 76.77,
        "mIwoC": 33.14,
        "commentWeight": 43.63,
        "kanDefect": 0.64,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.93,
        "relativeSystemComplexity": 121.93,
        "totalStructuralComplexity": 726,
        "totalDataComplexity": 5.58,
        "totalSystemComplexity": 731.58,
        "package": " OCA\\DocuDesk\\Controller\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\DocuDesk\\Controller\\PdfController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "render",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 2,
        "nbMethods": 2,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 7,
        "ccnMethodMax": 7,
        "externals": [
            "OCP\\AppFramework\\Controller",
            "OCP\\IRequest",
            "Psr\\Log\\LoggerInterface",
            "OCA\\DocuDesk\\Service\\PdfService",
            "OCP\\IL10N",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\DataDownloadResponse",
            "OCP\\AppFramework\\Http\\JSONResponse"
        ],
        "parents": [
            "OCP\\AppFramework\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 78,
        "vocabulary": 31,
        "volume": 386.43,
        "difficulty": 11.05,
        "effort": 4268.27,
        "level": 0.09,
        "bugs": 0.13,
        "time": 237,
        "intelligentContent": 34.99,
        "number_operators": 24,
        "number_operands": 54,
        "number_operators_unique": 9,
        "number_operands_unique": 22,
        "cloc": 37,
        "loc": 72,
        "lloc": 35,
        "mi": 92.06,
        "mIwoC": 47.26,
        "commentWeight": 44.8,
        "kanDefect": 0.43,
        "relativeStructuralComplexity": 49,
        "relativeDataComplexity": 0.69,
        "relativeSystemComplexity": 49.69,
        "totalStructuralComplexity": 98,
        "totalDataComplexity": 1.38,
        "totalSystemComplexity": 99.38,
        "package": " OCA\\DocuDesk\\Controller\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\DocuDesk\\Controller\\AnonymizationController",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "files",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "upload",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "extract",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "anonymize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 20,
        "ccn": 16,
        "ccnMethodMax": 8,
        "externals": [
            "OCP\\AppFramework\\Controller",
            "OCP\\IRequest",
            "Psr\\Log\\LoggerInterface",
            "OCA\\DocuDesk\\Service\\AnonymizationService",
            "OCA\\DocuDesk\\Service\\FileListingService",
            "OCP\\IL10N",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse",
            "OCP\\AppFramework\\Http\\JSONResponse"
        ],
        "parents": [
            "OCP\\AppFramework\\Controller"
        ],
        "implements": [],
        "lcom": 2,
        "length": 181,
        "vocabulary": 47,
        "volume": 1005.38,
        "difficulty": 21.77,
        "effort": 21888.57,
        "level": 0.05,
        "bugs": 0.34,
        "time": 1216,
        "intelligentContent": 46.18,
        "number_operators": 54,
        "number_operands": 127,
        "number_operators_unique": 12,
        "number_operands_unique": 35,
        "cloc": 74,
        "loc": 147,
        "lloc": 73,
        "mi": 80.72,
        "mIwoC": 36.18,
        "commentWeight": 44.54,
        "kanDefect": 0.57,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 1.13,
        "relativeSystemComplexity": 122.13,
        "totalStructuralComplexity": 605,
        "totalDataComplexity": 5.67,
        "totalSystemComplexity": 610.67,
        "package": " OCA\\DocuDesk\\Controller\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 7,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\DocuDesk\\AppInfo\\Application",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "register",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "boot",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 4,
        "ccn": 2,
        "ccnMethodMax": 2,
        "externals": [
            "OCP\\AppFramework\\App",
            "OCP\\AppFramework\\Bootstrap\\IBootstrap",
            "OCP\\AppFramework\\Bootstrap\\IRegistrationContext",
            "OCP\\AppFramework\\Bootstrap\\IBootContext"
        ],
        "parents": [
            "OCP\\AppFramework\\App"
        ],
        "implements": [
            "OCP\\AppFramework\\Bootstrap\\IBootstrap"
        ],
        "lcom": 3,
        "length": 19,
        "vocabulary": 8,
        "volume": 57,
        "difficulty": 2.67,
        "effort": 152,
        "level": 0.38,
        "bugs": 0.02,
        "time": 8,
        "intelligentContent": 21.38,
        "number_operators": 3,
        "number_operands": 16,
        "number_operators_unique": 2,
        "number_operands_unique": 6,
        "cloc": 33,
        "loc": 59,
        "lloc": 26,
        "mi": 102.38,
        "mIwoC": 56.57,
        "commentWeight": 45.81,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 36,
        "relativeDataComplexity": 0.14,
        "relativeSystemComplexity": 36.14,
        "totalStructuralComplexity": 108,
        "totalDataComplexity": 0.43,
        "totalSystemComplexity": 108.43,
        "package": "OCA\\DocuDesk\\AppInfo\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\DocuDesk\\Service\\MetadataService",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getObjectService",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "extractTextContent",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "enhanceTextMetadata",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "normalizeDateFields",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "enhanceMetadata",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "saveEnrichedMetadata",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 4,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 26,
        "ccn": 20,
        "ccnMethodMax": 7,
        "externals": [
            "Psr\\Log\\LoggerInterface",
            "Psr\\Container\\ContainerInterface",
            "OCP\\App\\IAppManager",
            "OCA\\DocuDesk\\Service\\TextAnalysisService",
            "OCA\\OpenRegister\\Service\\ObjectService",
            "RuntimeException",
            "DateTime",
            "Exception",
            "Exception",
            "Exception"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 222,
        "vocabulary": 53,
        "volume": 1271.6,
        "difficulty": 14.04,
        "effort": 17858.89,
        "level": 0.07,
        "bugs": 0.42,
        "time": 992,
        "intelligentContent": 90.54,
        "number_operators": 64,
        "number_operands": 158,
        "number_operators_unique": 8,
        "number_operands_unique": 45,
        "cloc": 78,
        "loc": 176,
        "lloc": 98,
        "mi": 75.04,
        "mIwoC": 32.14,
        "commentWeight": 42.9,
        "kanDefect": 1.22,
        "relativeStructuralComplexity": 361,
        "relativeDataComplexity": 0.44,
        "relativeSystemComplexity": 361.44,
        "totalStructuralComplexity": 2527,
        "totalDataComplexity": 3.1,
        "totalSystemComplexity": 2530.1,
        "package": " OCA\\DocuDesk\\Service\\",
        "pageRank": 0.08,
        "afferentCoupling": 2,
        "efferentCoupling": 8,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "OCA\\DocuDesk\\Service\\TemplateService",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getObjectService",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRegisterAndSchema",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "validateNamespace",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTemplates",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "deleteTemplate",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTemplatesByNamespace",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 10,
        "nbMethods": 10,
        "nbMethodsPrivate": 3,
        "nbMethodsPublic": 7,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 26,
        "ccn": 17,
        "ccnMethodMax": 6,
        "externals": [
            "Psr\\Container\\ContainerInterface",
            "OCP\\App\\IAppManager",
            "OCA\\DocuDesk\\Service\\SettingsService",
            "OCA\\OpenRegister\\Service\\ObjectService",
            "RuntimeException",
            "Exception",
            "Exception",
            "Exception",
            "Exception",
            "Exception",
            "Exception"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 220,
        "vocabulary": 55,
        "volume": 1271.9,
        "difficulty": 13.19,
        "effort": 16778.24,
        "level": 0.08,
        "bugs": 0.42,
        "time": 932,
        "intelligentContent": 96.42,
        "number_operators": 65,
        "number_operands": 155,
        "number_operators_unique": 8,
        "number_operands_unique": 47,
        "cloc": 117,
        "loc": 216,
        "lloc": 99,
        "mi": 77.88,
        "mIwoC": 32.44,
        "commentWeight": 45.44,
        "kanDefect": 0.85,
        "relativeStructuralComplexity": 196,
        "relativeDataComplexity": 0.89,
        "relativeSystemComplexity": 196.89,
        "totalStructuralComplexity": 1960,
        "totalDataComplexity": 8.87,
        "totalSystemComplexity": 1968.87,
        "package": " OCA\\DocuDesk\\Service\\",
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 6,
        "instability": 0.86,
        "violations": {}
    },
    {
        "name": "OCA\\DocuDesk\\Service\\TextAnalysisService",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "countWordOccurrences",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "detectLanguage",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "extractKeywords",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "classifyTopic",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "standardizeDocumentType",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 14,
        "ccn": 10,
        "ccnMethodMax": 4,
        "externals": [],
        "parents": [],
        "implements": [],
        "lcom": 3,
        "length": 229,
        "vocabulary": 105,
        "volume": 1537.56,
        "difficulty": 8.86,
        "effort": 13621.84,
        "level": 0.11,
        "bugs": 0.51,
        "time": 757,
        "intelligentContent": 173.55,
        "number_operators": 40,
        "number_operands": 189,
        "number_operators_unique": 9,
        "number_operands_unique": 96,
        "cloc": 50,
        "loc": 112,
        "lloc": 62,
        "mi": 80.24,
        "mIwoC": 37.24,
        "commentWeight": 43,
        "kanDefect": 1.12,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 5.1,
        "relativeSystemComplexity": 6.1,
        "totalStructuralComplexity": 5,
        "totalDataComplexity": 25.5,
        "totalSystemComplexity": 30.5,
        "package": " OCA\\DocuDesk\\Service\\",
        "pageRank": 0.07,
        "afferentCoupling": 1,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "OCA\\DocuDesk\\Service\\ConsentService",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getObjectService",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getObjectionPeriodDays",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "createConsentRequest",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateConsentStatus",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "checkObjectionDeadline",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getConsentsByDocument",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 7,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 19,
        "ccn": 13,
        "ccnMethodMax": 5,
        "externals": [
            "Psr\\Log\\LoggerInterface",
            "Psr\\Container\\ContainerInterface",
            "OCP\\App\\IAppManager",
            "OCP\\IAppConfig",
            "OCA\\OpenRegister\\Service\\ObjectService",
            "RuntimeException",
            "DateTime",
            "Exception",
            "Exception",
            "Exception",
            "Exception",
            "DateTime",
            "DateTime",
            "Exception",
            "Exception"
        ],
        "parents": [],
        "implements": [],
        "lcom": 1,
        "length": 249,
        "vocabulary": 65,
        "volume": 1499.57,
        "difficulty": 15.43,
        "effort": 23136.22,
        "level": 0.06,
        "bugs": 0.5,
        "time": 1285,
        "intelligentContent": 97.19,
        "number_operators": 57,
        "number_operands": 192,
        "number_operators_unique": 9,
        "number_operands_unique": 56,
        "cloc": 99,
        "loc": 192,
        "lloc": 93,
        "mi": 77.91,
        "mIwoC": 33.07,
        "commentWeight": 44.84,
        "kanDefect": 0.73,
        "relativeStructuralComplexity": 256,
        "relativeDataComplexity": 0.58,
        "relativeSystemComplexity": 256.58,
        "totalStructuralComplexity": 1792,
        "totalDataComplexity": 4.06,
        "totalSystemComplexity": 1796.06,
        "package": " OCA\\DocuDesk\\Service\\",
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 8,
        "instability": 0.89,
        "violations": {}
    },
    {
        "name": "OCA\\DocuDesk\\Service\\FileListingService",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isOpenRegisterInstalled",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getEntityRelationMapper",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getRiskLevelService",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getCurrentUserId",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "tryGetEntityRelationMapper",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "tryGetRiskLevelService",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getEntityStats",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "determineFileStatus",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getFileRiskLevel",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildFileInfo",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "listProcessedFiles",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getDocuDeskFolder",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "resolveUniqueFileName",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "uploadFile",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 15,
        "nbMethods": 15,
        "nbMethodsPrivate": 12,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 39,
        "ccn": 25,
        "ccnMethodMax": 6,
        "externals": [
            "Psr\\Log\\LoggerInterface",
            "Psr\\Container\\ContainerInterface",
            "OCP\\App\\IAppManager",
            "OCP\\Files\\IRootFolder",
            "OCP\\IUserSession",
            "OCA\\OpenRegister\\Db\\EntityRelationMapper",
            "RuntimeException",
            "OCA\\OpenRegister\\Service\\RiskLevelService",
            "RuntimeException",
            "Exception",
            "OCP\\Files\\File",
            "Exception",
            "OCP\\Files\\Folder",
            "Exception",
            "OCP\\Files\\Folder",
            "Exception"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 364,
        "vocabulary": 78,
        "volume": 2287.89,
        "difficulty": 18.6,
        "effort": 42561.42,
        "level": 0.05,
        "bugs": 0.76,
        "time": 2365,
        "intelligentContent": 122.99,
        "number_operators": 111,
        "number_operands": 253,
        "number_operators_unique": 10,
        "number_operands_unique": 68,
        "cloc": 136,
        "loc": 311,
        "lloc": 175,
        "mi": 66.91,
        "mIwoC": 24.19,
        "commentWeight": 42.72,
        "kanDefect": 1.82,
        "relativeStructuralComplexity": 1444,
        "relativeDataComplexity": 0.65,
        "relativeSystemComplexity": 1444.65,
        "totalStructuralComplexity": 21660,
        "totalDataComplexity": 9.69,
        "totalSystemComplexity": 21669.69,
        "package": " OCA\\DocuDesk\\Service\\",
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 11,
        "instability": 0.92,
        "violations": {}
    },
    {
        "name": "OCA\\DocuDesk\\Service\\PdfService",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "renderPdf",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "renderTemplate",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "ensureTempDirectory",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "buildMpdfConfig",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generatePdf",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 6,
        "nbMethods": 6,
        "nbMethodsPrivate": 4,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 18,
        "ccn": 13,
        "ccnMethodMax": 8,
        "externals": [
            "Psr\\Log\\LoggerInterface",
            "Twig\\Loader\\ArrayLoader",
            "Twig\\Environment",
            "Twig\\Sandbox\\SecurityPolicy",
            "Twig\\Extension\\SandboxExtension",
            "Exception",
            "Mpdf\\Mpdf",
            "Exception"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 180,
        "vocabulary": 88,
        "volume": 1162.7,
        "difficulty": 7.4,
        "effort": 8603.96,
        "level": 0.14,
        "bugs": 0.39,
        "time": 478,
        "intelligentContent": 157.12,
        "number_operators": 32,
        "number_operands": 148,
        "number_operators_unique": 8,
        "number_operands_unique": 80,
        "cloc": 94,
        "loc": 153,
        "lloc": 59,
        "mi": 85.01,
        "mIwoC": 38.16,
        "commentWeight": 46.86,
        "kanDefect": 0.29,
        "relativeStructuralComplexity": 121,
        "relativeDataComplexity": 0.49,
        "relativeSystemComplexity": 121.49,
        "totalStructuralComplexity": 726,
        "totalDataComplexity": 2.92,
        "totalSystemComplexity": 728.92,
        "package": " OCA\\DocuDesk\\Service\\",
        "pageRank": 0.06,
        "afferentCoupling": 1,
        "efferentCoupling": 7,
        "instability": 0.88,
        "violations": {}
    },
    {
        "name": "OCA\\DocuDesk\\Service\\SettingsService",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isOpenRegisterInstalled",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isOpenRegisterEnabled",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getObjectService",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getConfigurationService",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "initialize",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadSettings",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fetchAvailableRegisters",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "serializeRegister",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "filterSchemaProperties",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadObjectTypeConfiguration",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "loadFeatureToggles",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getAllSettings",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "convertValueToString",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "updateSettings",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 15,
        "nbMethods": 15,
        "nbMethodsPrivate": 10,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 43,
        "ccn": 29,
        "ccnMethodMax": 6,
        "externals": [
            "OCP\\IAppConfig",
            "Psr\\Container\\ContainerInterface",
            "OCP\\App\\IAppManager",
            "Psr\\Log\\LoggerInterface",
            "OCA\\OpenRegister\\Service\\RegisterService",
            "RuntimeException",
            "RuntimeException",
            "RuntimeException",
            "RuntimeException",
            "RuntimeException",
            "RuntimeException",
            "RuntimeException",
            "RuntimeException",
            "RuntimeException",
            "RuntimeException",
            "RuntimeException",
            "RuntimeException"
        ],
        "parents": [],
        "implements": [],
        "lcom": 3,
        "length": 390,
        "vocabulary": 101,
        "volume": 2596.7,
        "difficulty": 15.22,
        "effort": 39521.24,
        "level": 0.07,
        "bugs": 0.87,
        "time": 2196,
        "intelligentContent": 170.61,
        "number_operators": 113,
        "number_operands": 277,
        "number_operators_unique": 10,
        "number_operands_unique": 91,
        "cloc": 151,
        "loc": 337,
        "lloc": 186,
        "mi": 65.73,
        "mIwoC": 22.68,
        "commentWeight": 43.04,
        "kanDefect": 1.73,
        "relativeStructuralComplexity": 576,
        "relativeDataComplexity": 0.87,
        "relativeSystemComplexity": 576.87,
        "totalStructuralComplexity": 8640,
        "totalDataComplexity": 13.04,
        "totalSystemComplexity": 8653.04,
        "package": " OCA\\DocuDesk\\Service\\",
        "pageRank": 0.1,
        "afferentCoupling": 4,
        "efferentCoupling": 6,
        "instability": 0.6,
        "violations": {}
    },
    {
        "name": "OCA\\DocuDesk\\Service\\AnonymizationService",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getOpenRegisterService",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "normalizeEntities",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "extractAndDetectEntities",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "shouldSkipEntity",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "mapEntitiesForAnonymization",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "extractResultFromObject",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "extractResultFromArray",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "parseAnonymizationResult",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "anonymizeDocument",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "generateUuid",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 11,
        "nbMethods": 11,
        "nbMethodsPrivate": 8,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 42,
        "ccn": 32,
        "ccnMethodMax": 9,
        "externals": [
            "Psr\\Log\\LoggerInterface",
            "Psr\\Container\\ContainerInterface",
            "OCP\\App\\IAppManager",
            "RuntimeException",
            "Exception",
            "Exception"
        ],
        "parents": [],
        "implements": [],
        "lcom": 2,
        "length": 303,
        "vocabulary": 81,
        "volume": 1920.97,
        "difficulty": 18.61,
        "effort": 35746.83,
        "level": 0.05,
        "bugs": 0.64,
        "time": 1986,
        "intelligentContent": 103.23,
        "number_operators": 89,
        "number_operands": 214,
        "number_operators_unique": 12,
        "number_operands_unique": 69,
        "cloc": 107,
        "loc": 217,
        "lloc": 110,
        "mi": 72.46,
        "mIwoC": 28.17,
        "commentWeight": 44.28,
        "kanDefect": 1.17,
        "relativeStructuralComplexity": 484,
        "relativeDataComplexity": 0.62,
        "relativeSystemComplexity": 484.62,
        "totalStructuralComplexity": 5324,
        "totalDataComplexity": 6.83,
        "totalSystemComplexity": 5330.83,
        "package": " OCA\\DocuDesk\\Service\\",
        "pageRank": 0.04,
        "afferentCoupling": 1,
        "efferentCoupling": 5,
        "instability": 0.83,
        "violations": {}
    },
    {
        "name": "OCA\\DocuDesk\\EventListener\\DocuDeskEventListener",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "dispatchEvent",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "logHandlerError",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "isEnrichmentEnabled",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "runEnrichment",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handleObjectCreated",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "hasContentChanged",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handleObjectUpdated",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "handleObjectDeleted",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 10,
        "nbMethods": 10,
        "nbMethodsPrivate": 8,
        "nbMethodsPublic": 2,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 34,
        "ccn": 25,
        "ccnMethodMax": 6,
        "externals": [
            "OCP\\EventDispatcher\\IEventListener",
            "OCP\\EventDispatcher\\Event",
            "OCP\\EventDispatcher\\Event",
            "OCA\\DocuDesk\\Service\\MetadataService",
            "OCA\\DocuDesk\\Service\\SettingsService",
            "Psr\\Log\\LoggerInterface",
            "Exception",
            "OCP\\EventDispatcher\\Event",
            "OCA\\DocuDesk\\Service\\SettingsService",
            "OCA\\DocuDesk\\Service\\MetadataService",
            "Psr\\Log\\LoggerInterface",
            "OCA\\OpenRegister\\Event\\ObjectCreatedEvent",
            "OCA\\DocuDesk\\Service\\MetadataService",
            "OCA\\DocuDesk\\Service\\SettingsService",
            "Psr\\Log\\LoggerInterface",
            "OCA\\OpenRegister\\Event\\ObjectUpdatedEvent",
            "OCA\\DocuDesk\\Service\\MetadataService",
            "OCA\\DocuDesk\\Service\\SettingsService",
            "Psr\\Log\\LoggerInterface",
            "OCA\\OpenRegister\\Event\\ObjectDeletedEvent",
            "Psr\\Log\\LoggerInterface"
        ],
        "parents": [],
        "implements": [
            "OCP\\EventDispatcher\\IEventListener"
        ],
        "lcom": 2,
        "length": 297,
        "vocabulary": 64,
        "volume": 1782,
        "difficulty": 18.49,
        "effort": 32950.8,
        "level": 0.05,
        "bugs": 0.59,
        "time": 1831,
        "intelligentContent": 96.37,
        "number_operators": 71,
        "number_operands": 226,
        "number_operators_unique": 9,
        "number_operands_unique": 55,
        "cloc": 112,
        "loc": 240,
        "lloc": 128,
        "mi": 71.48,
        "mIwoC": 27.91,
        "commentWeight": 43.58,
        "kanDefect": 1.22,
        "relativeStructuralComplexity": 784,
        "relativeDataComplexity": 0.47,
        "relativeSystemComplexity": 784.47,
        "totalStructuralComplexity": 7840,
        "totalDataComplexity": 4.72,
        "totalSystemComplexity": 7844.72,
        "package": " OCA\\DocuDesk\\EventListener\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 9,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\DocuDesk\\Sections\\DocuDeskAdmin",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getIcon",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getID",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getName",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPriority",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 5,
        "nbMethods": 5,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 5,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 5,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "OCP\\Settings\\IIconSection",
            "OCP\\IL10N",
            "OCP\\IURLGenerator"
        ],
        "parents": [],
        "implements": [
            "OCP\\Settings\\IIconSection"
        ],
        "lcom": 3,
        "length": 19,
        "vocabulary": 9,
        "volume": 60.23,
        "difficulty": 1.86,
        "effort": 111.85,
        "level": 0.54,
        "bugs": 0.02,
        "time": 6,
        "intelligentContent": 32.43,
        "number_operators": 6,
        "number_operands": 13,
        "number_operators_unique": 2,
        "number_operands_unique": 7,
        "cloc": 67,
        "loc": 94,
        "lloc": 27,
        "mi": 104.46,
        "mIwoC": 56.18,
        "commentWeight": 48.28,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 1.47,
        "relativeSystemComplexity": 5.47,
        "totalStructuralComplexity": 20,
        "totalDataComplexity": 7.33,
        "totalSystemComplexity": 27.33,
        "package": " OCA\\DocuDesk\\Sections\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\DocuDesk\\Dashboard\\AnonymizationWidget",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTitle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getOrder",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getIconClass",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getIconUrl",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUrl",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "load",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "OCP\\Dashboard\\IWidget",
            "OCP\\Dashboard\\IIconWidget",
            "OCP\\IURLGenerator",
            "OCP\\Util"
        ],
        "parents": [],
        "implements": [
            "OCP\\Dashboard\\IWidget",
            "OCP\\Dashboard\\IIconWidget"
        ],
        "lcom": 7,
        "length": 17,
        "vocabulary": 10,
        "volume": 56.47,
        "difficulty": 0.61,
        "effort": 34.51,
        "level": 1.64,
        "bugs": 0.02,
        "time": 2,
        "intelligentContent": 92.41,
        "number_operators": 6,
        "number_operands": 11,
        "number_operators_unique": 1,
        "number_operands_unique": 9,
        "cloc": 59,
        "loc": 94,
        "lloc": 35,
        "mi": 101,
        "mIwoC": 53.92,
        "commentWeight": 47.08,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 1.23,
        "relativeSystemComplexity": 17.23,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 9.8,
        "totalSystemComplexity": 137.8,
        "package": " OCA\\DocuDesk\\Dashboard\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\DocuDesk\\Dashboard\\FileEntitiesWidget",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getId",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getTitle",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getOrder",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getIconClass",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getIconUrl",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getUrl",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "load",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 8,
        "nbMethods": 8,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 8,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 8,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "OCP\\Dashboard\\IWidget",
            "OCP\\Dashboard\\IIconWidget",
            "OCP\\IURLGenerator",
            "OCP\\Util"
        ],
        "parents": [],
        "implements": [
            "OCP\\Dashboard\\IWidget",
            "OCP\\Dashboard\\IIconWidget"
        ],
        "lcom": 7,
        "length": 17,
        "vocabulary": 10,
        "volume": 56.47,
        "difficulty": 0.61,
        "effort": 34.51,
        "level": 1.64,
        "bugs": 0.02,
        "time": 2,
        "intelligentContent": 92.41,
        "number_operators": 6,
        "number_operands": 11,
        "number_operators_unique": 1,
        "number_operands_unique": 9,
        "cloc": 59,
        "loc": 94,
        "lloc": 35,
        "mi": 101,
        "mIwoC": 53.92,
        "commentWeight": 47.08,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 16,
        "relativeDataComplexity": 1.23,
        "relativeSystemComplexity": 17.23,
        "totalStructuralComplexity": 128,
        "totalDataComplexity": 9.8,
        "totalSystemComplexity": 137.8,
        "package": " OCA\\DocuDesk\\Dashboard\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 4,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "OCA\\DocuDesk\\Settings\\DocuDeskAdmin",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": "setter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getForm",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getSection",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "getPriority",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 4,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 1,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "OCP\\Settings\\ISettings",
            "OCP\\App\\IAppManager",
            "OCP\\AppFramework\\Http\\TemplateResponse",
            "OCP\\AppFramework\\Http\\TemplateResponse"
        ],
        "parents": [],
        "implements": [
            "OCP\\Settings\\ISettings"
        ],
        "lcom": 3,
        "length": 17,
        "vocabulary": 9,
        "volume": 53.89,
        "difficulty": 1.71,
        "effort": 92.38,
        "level": 0.58,
        "bugs": 0.02,
        "time": 5,
        "intelligentContent": 31.44,
        "number_operators": 5,
        "number_operands": 12,
        "number_operators_unique": 2,
        "number_operands_unique": 7,
        "cloc": 51,
        "loc": 73,
        "lloc": 22,
        "mi": 106.57,
        "mIwoC": 58.46,
        "commentWeight": 48.11,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1.63,
        "relativeSystemComplexity": 2.63,
        "totalStructuralComplexity": 4,
        "totalDataComplexity": 6.5,
        "totalSystemComplexity": 10.5,
        "package": " OCA\\DocuDesk\\Settings\\",
        "pageRank": 0.04,
        "afferentCoupling": 0,
        "efferentCoupling": 3,
        "instability": 1,
        "violations": {}
    }
]